### ISSUE TITLE
typo in javascript driver docs

### ISSUE THREAD

**Issue by Lenostatos** [neo4j/driver-documentation#392]
https://github.com/neo4j/docs-drivers/blob/40c938dd7407914579e74844f3de3c187892af53/javascript-manual/modules/ROOT/pages/query-simple.adoc?plain=1#L48

this line is missing a comma at the end

**Comment by stefano-ottolenghi** [comment]
Thanks! Fixed https://github.com/neo4j/docs-drivers/commit/e5e23c65c24b608cf3f96118f80d67a643ab32d0
