### ISSUE TITLE
Missleading Comment

### ISSUE THREAD

**Issue by Raphael2b3** [neo4j/driver-documentation#403]
https://github.com/neo4j/docs-drivers/blame/10b6234d77a94757eba4b744051725a4c261a4a2/python-manual/modules/ROOT/pages/transformers.adoc#L20C45-L20C45

Its not true that this is valid, you have to put the field name in ["fieldname"]

example:

for record in records:
    print(record["fieldname"])
    
    # works

for record in records:
    print(record.fieldname)
    
    # doesnt work

**Comment by stefano-ottolenghi** [comment]
Good catch, and thanks for reporting! Fixed in https://github.com/neo4j/docs-drivers/commit/d0a38140db18603a2cfaac8420dc321ead817316 and live already :)
