### ISSUE TITLE
Javscript Code Snippets aren't displayed properly

### ISSUE THREAD

**Issue by felixf2k** [neo4j/driver-documentation#447]
![image](https://github.com/user-attachments/assets/fa9e7b7f-569a-443c-bb76-f8ac5ab893a5)

Instead of the code being rendered a list of `[object Object]` is rendered.

i have tried:
- reloading the page
- clearing the cache
- different browsers

## Tested Browsers:
- Chromium Version 129.0.6668.58 (Official Build) (64-bit)
- Firefox 130.0.1 (64-bit)
- Edge Version 129.0.2792.52 (Official build) (64-bit)

The problem persists in all tested browsers.
The copy button next to the code snippets is woking, so i can paste the code elsewhere.

**Comment by felixf2k** [comment]
It works now, thank you for the quick fix

**Comment by recrwplay** [comment]
Hi @felixf2k - thanks for letting us know about this issue. As you've seen we've now got a fix in place so code blocks are rendered correctly again.
